### ISSUE TITLE
Installation documentation address incorrect

### ISSUE THREAD

**Issue by graememck** [i-lateral/silverstripe-catalogue#12]
Should be:

https://github.com/i-lateral/silverstripe-catalogue/blob/master/docs/en/Installation.md

**Comment by mlewis-everley** [comment]
Sorry, I am not sure to what this issue refers? The URL provided links to installation docs?

**Comment by graememck** [comment]
I should have made this clearer: if you click on the current installation link it doesn't work. The url is missing a letter (instalation instead of installation)

**Comment by mlewis-everley** [comment]
Ok, I have updated the link from Index.md (I am guessing this is what you meant)? Also updated the docs slightly.
